spring:
  profiles:
    active: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/psychotherapy}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB      # Максимальний розмір одного файлу
      max-request-size: 10MB   # Максимальний розмір усього запиту
    session:
      persistent: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
server:
  servlet:
    session:
      persistent: false
  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: false

app:
  public-base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  crypto:
    secret-key: ${MMC_CRYPTO_KEY}
  upload-dir: ${APP_UPLOAD_DIR:./uploads/articles} # 2. ДОДАЄМО ШЛЯХ ДО ЗАХИЩЕНОЇ ПАПКИ МЕДІА
  oauth2:
    google:
      client-id: ${OAUTH2_GOOGLE_CLIENT_ID:dummy}
      client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:dummy}
    facebook:
      client-id: ${OAUTH2_FACEBOOK_CLIENT_ID:dummy}
      client-secret: ${OAUTH2_FACEBOOK_CLIENT_SECRET:dummy}
